### ISSUE TITLE
Doc | Namespaces

### ISSUE THREAD

**Issue by anarolon** [anarolon/person-and-ghost#11]
- [x] Watch video on how to use Namespaces
- [x] Implement an example in C# with Unity
### Velocity = 1

**Comment by A4Michael** [comment]
# Setup a root namespace in the project so all the scripts can live under the same custom namespace (*optional but good practice*)
1. Inside Unity click Edit
2. Click Project Settings
3. Click C# Project Generation
4. Click Root namespace
5. Select a name
6. **Optional**: check if the assembly project's properties point to root namespace
# Divide code into meaningful boundaries with namespaces so that it's easier to maintain, scale, and understand 
1. Change project view to solution
2. Describe what each script does
3. Design the meaningful boundaries of the code (core, certain object,... ) ***(this is an iterative step)***
4. Create directories with the names of those boundaries
5. Move scripts relating to each name inside its corresponding directory
6. Adjust namespace of each file
