### ISSUE TITLE
Doc | Unit Tests

### ISSUE THREAD

**Issue by anarolon** [anarolon/person-and-ghost#12]
- [x] Understand how to implement and run Unit Test for Unity projects
- [x] Implement an example in C# with Unity for documentation
### Velocity = 1

**Comment by A4Michael** [comment]
# Creating Unit Tests
### Different types of unit tests in Unity
- Play Mode tests code that needs to be run with a scene for it to work properly
- Edit Mode tests can be run independently
### Create Tests directory
1. In Unity, right-click Assets folder inside the Project window
2. Click Create
3. Click Folder
4. Name folder Tests
### Open Test run window
1. Click Window
2. Click General
3. Click Test Runner
### Create Test Assembly Folder
1. Select Tests folder in Project window
2. Select Play Mode or EditMode inside the Test Runner window
3. Click Create Test Assembly Folder and name it EditMode or PlayMode accordingly
4. If not done previously associate all scripts to an assembly so that the tests can see them
5. Add the corresponding assembly of the scripts to the relevant test assembly reference
### Create Test Script
1. Click Create Test Script in the current folder
5. Give it a relevant name
8. Open the test file
9. Remove the boiler plate code except the [Test] method for EditMode and [UnityTest] for PlayMode
10. Rename test accordingly
11. Write an assert test. (**Example:** `Assert.AreEqual(*expected*, *actual*);`)
### Run tests
1. In Unity's Test Runner, find test by expanding the arrows
2. Select the test to run
3. Click Run Selected
4. **Optional:** to run every test, click run all
