### ISSUE TITLE
Dev | Implement Player Meditation Ability

### ISSUE THREAD

**Issue by YenielDiaz** [anarolon/person-and-ghost#23]
- [x] Make Player Stationary While Active
- [x] Implement Extended Range for which Ghost can move in
- [x] Test the functionality implemented.
- [x] Brainstorm MicroGame to have Player have to play in order to maintain concentration
   - Tetris-like
   - Rhythm Game like "Friday Night Funking" ?
   - Basic Quick Time Event (QTE)

**Comment by A4Michael** [comment]
## Brainstorming results
After considering simple games like party games of the _Jackbox_ and _Mario Party_ series, mini-games like _Wario Ware_ ones, and old arcade games; one can see that the options may seem endless. However, the game selected should not only be intrusive and not feel like a shore but also feel fun and as part of the world, as if Person is fighting to give ghost more time. Since, the activity is meditation the mini-game should reflect the difficulties of concentration in limbo. A quick-time event may be too much action in a moment but a simple puzzle could be boring and tedious. Arcade games like rhythm, fighting, or fixed shooters can hit that sweet spot between adding more action but not breaking the flow of the game.
