### ISSUE TITLE
Dev | Decide if we are going to use Pixel Art, Vector, or Hand Drawn art

### ISSUE THREAD

**Issue by A4Michael** [anarolon/person-and-ghost#28]
### Person or Ghost Concepts
- [x] Pixel Art POC
- [x] Vector POC
- [x] Hand-drawn POC

**Comment by jeanrodriguez27** [comment]
Issue was resolved, it was determined that the use of pixel art would be the most appropriate choice of the two given the fact that it would reduce the workload on the team's shoulders when it comes to the visuals of the project. This is due to the fact that not only is there is a greater abundance of Unity assets which employ pixel art compared to hand drawn or vector art, but also because the team found pixel art designs easier to create and animate than the aforementioned alternative.
