### ISSUE TITLE
DOC | Feedback Criteria Document

### ISSUE THREAD

**Issue by A4Michael** [anarolon/person-and-ghost#31]
- [x] Brainstorm the main topics the teams want feedback
- [x] Devise questions that are objective and get feedback from each topic
- [x] Create a form to get feedback from the questions
- [x] Analyze feedback got from the form and prepare a document to house this analysis

**Comment by jeanrodriguez27** [comment]
Under construction, here's how it looks for now:

https://docs.google.com/forms/d/e/1FAIpQLSfXjOKd5Z812HxIdQldxmhTXCMbqgXzg9kyid6J3b_0K8OI7A/viewform?usp=pp_url

**Comment by jeanrodriguez27** [comment]
Due to limitations on time, all testing was performed by members of the team. The necessary document itself is completed and approved by the team for use in future work whenever others are invited to test the game ( See Issue #37 ).

All members have editor permissions on this form when using their UPR emails. They can reach it with this link:
https://docs.google.com/forms/d/1zlE4DCzI4DReZp2-Hylz2Zm9RGIlU6GQ29i9vqmgay0/edit?usp=sharing
